### ISSUE TITLE
Restrict install popup

### ISSUE THREAD

**Issue by arnaud-1510** [dynamsoft-dwt/web-twain-package#1]
I been trying to restrict to an specific component the installation prompt for the plugin is this possible  using this package, do you have any sort of guide or tutorial for this also I've read the docs and haven't found anything related to this.

Could please give any ideas?

**Comment by Tom-Dynamsoft** [comment]
@arnaud-1510  Sorry for the long delay.. Anyway, if you are still interested, what you need should be to initiate the package only when a certain component is loaded/used. This can restrict the installation prompt. (The default behavior is to initiate the package on page load which would mean the prompt comes up immediately)
